Multi signal declaration extraction
google/verible pull request #423
Opened 2020-09-02 14:27 UTC by MinaToma

Fixes #422

2020-09-02 15:35 UTC, ivan444 approved these changes

2020-09-03 01:15 UTC, fangism requested changes
Thanks for fixing!

2020-09-03 01:15 UTC, fangism commented on verilog/CST/identifier_test.cc
> +  const SyntaxTreeSearchTestCase kTestCases[] = {
Suggested test cases:

* including unpacked identifiers like `b[M:N]`
* with a net type like `input wire`

2020-09-03 01:15 UTC, fangism commented on verilog/CST/identifier.h
> +// Extracts SymbolIdentifier leaf from a kIdentifierUnpackedDimensions node;
example: extracts "a" from "a[0:1]"

2020-09-03 01:15 UTC, fangism commented on verilog/tools/kythe/indexing_facts_tree_extractor_test.cc
> +  const verible::SyntaxTreeSearchTestCase kTestCase = {{"module ",
Suggest adding unpacked dimensions to at least one of the ports.

2020-09-03 15:51 UTC, fangism approved these changes

2020-09-08 18:17 UTC, hzeller commented
Similar with #417, this one has got a conflict after #415 was merged. Could you have a look to consolidate the file ?

2020-09-09 16:09 UTC, fangism approved these changes

2020-09-09 16:28 UTC, closed without merging