Class hierarchy extractor
google/verible pull request #534
Opened 2020-10-14 13:50 UTC by MinaToma

Fixes #487

2020-10-14 13:50 UTC, MinaToma commented
No Tests added yet ==> WIP.

2020-10-14 16:57 UTC, fangism commented
> No Tests added yet ==> WIP.

Acknowledged.

2020-10-14 17:37 UTC, fangism requested changes
I know you're still preparing other tests.

2020-10-14 17:37 UTC, fangism commented on verilog/CST/class.cc
> +  return AutoUnwrapIdentifier(verible::GetSubtreeAsNode(
What if you have a qualified class name?

```systemverilog
class C extends p_pkg::A;
endclass
class C extends p_pkg::X::Y;
endclass
```

2020-10-14 17:37 UTC, fangism commented on verilog/tools/kythe/testdata/more_testdata/class_extends.sv
> +       $display(instance1::instance2::var2);
Suggest a test case that references `instance1.var1`.

2020-10-15 08:41 UTC, MinaToma commented on verilog/tools/kythe/testdata/more_testdata/class_extends.sv
> +       $display(instance1::instance2::var2);
Depends on PR #533

2020-10-15 12:59 UTC, ivan444 approved these changes

2020-10-16 09:24 UTC, fangism approved these changes

2020-10-16 09:52 UTC, closed without merging