Interfaces and Programs Extractor
google/verible pull request #539
Opened 2020-10-15 13:28 UTC by MinaToma

Fixes #467

also extracts facts for `program`

2020-10-15 13:30 UTC, MinaToma commented
Opening PR for early review.
Not tests yet.

Tests depend on PR #533

2020-10-15 13:56 UTC, ivan444 requested changes

2020-10-15 13:56 UTC, ivan444 commented on verilog/CST/module.cc
> +      verible::GetSubtreeAsLeaf(*header_node, NodeEnum::kModuleHeader, 2);
check if `header_node` is null?

2020-10-15 13:56 UTC, ivan444 commented on verilog/CST/module.cc
> +      verible::GetSubtreeAsLeaf(*header_node, NodeEnum::kModuleHeader, 2);
also, elsewhere

2020-10-15 13:56 UTC, ivan444 commented on verilog/CST/module.cc
> +const verible::SyntaxTreeNode* GetModuleItemList(
(no action required)

Eh, it'd be nice to use something like absl::optional :).

2020-10-15 13:56 UTC, ivan444 commented on verilog/tools/kythe/indexing_facts_tree_extractor.cc
> +  ExtractModuleAndInterfaceAndProgram(program_declaration_node, program_node);
s/And/Or/?

2020-10-15 13:56 UTC, ivan444 commented on verilog/tools/kythe/testdata/more_testdata/primitive_type_with_dimensions.sv
> +//- @core_ibex_instr_monitor_if defines/binding _
can we drop "ibex" from here? it's somewhat confusing if you don't have the context

2020-10-15 16:21 UTC, fangism requested changes
Implementation looks ok.  Minor things.

2020-10-15 16:21 UTC, fangism commented on verilog/CST/module.cc
> +                                    NodeEnum::kProgramDeclaration})) {
Since this logic appears more than one place, factor out a function for this somewhere.

2020-10-15 16:21 UTC, fangism commented on verilog/tools/kythe/testdata/more_testdata/basics.sv
> +
End file with a newline.

2020-10-15 16:21 UTC, fangism commented on verilog/tools/kythe/testdata/more_testdata/interface_with_module.sv
> +interface Bus;
suggest a test case somewhere with a parameterized interface, similar to parameterized module.

2020-10-16 14:38 UTC, MinaToma commented
moved to #541.

2020-10-16 14:38 UTC, closed without merging