Function named arguments
google/verible pull request #554
Opened 2020-10-25 17:10 UTC by MinaToma

Fixes #537

2020-10-25 22:07 UTC, fangism requested changes
Minor fix only.

2020-10-25 22:07 UTC, fangism commented on verilog/tools/kythe/indexing_facts_tree_extractor_test.cc
> +TEST(FactsTreeExtractor, FunctinoNamedArgument) {
FunctionNamedArgument

2020-10-26 12:31 UTC, ivan444 approved these changes

2020-10-26 16:58 UTC, fangism approved these changes

2020-10-27 20:41 UTC, closed without merging