pure virtual function and pure virtual task
google/verible pull request #577
Opened 2020-11-06 12:35 UTC by MinaToma

Fixes #437

2020-11-06 12:55 UTC, ivan444 approved these changes

2020-11-06 18:04 UTC, fangism requested changes
Main concerns:
* Functions that used to marked as complete are no longer marked complete.
* Distinction between forward declaration and full definition (completeness) seems missing.

2020-11-09 07:35 UTC, MinaToma commented on verilog/tools/kythe/indexing_facts_tree_extractor_test.cc
> +  };
This is not working yet. and we have an issue for it.

2020-11-09 07:36 UTC, MinaToma commented on verilog/tools/kythe/kythe_facts_extractor.cc
> +  // TODO(minatoma): add function.complete or function.incomplete if needed.
It's easy to add or remove them. I didn't add them at the moment as I wanted to see if there is a difference. but I will add them now.

2020-11-09 09:42 UTC, fangism approved these changes

2020-11-09 10:11 UTC, closed without merging