[CI] enable github actions
google/verible pull request #603
Opened 2020-11-13 17:08 UTC by wtatarski

2020-11-13 18:35 UTC, mithro commented
@wtatarski - Looks like these are failing on your repository at https://github.com/antmicro/verible/actions/runs/362003112 ?

2020-11-13 18:47 UTC, fangism requested changes
Mostly looks good to me, but I have less experience setting these up.

2020-11-13 18:47 UTC, fangism commented on .github/workflows/script.sh
> +    bazel build -c opt --noshow_progress "${BAZEL_CXXOPTS[@]}" //...
Both should use `-c opt` consistently so the two commands share the cache.  (Reminder: `CHECK`s in our code are always-on unaffected by `NDEBUG`)

BTW, I'm not opposed running a duplicate job without `-c opt` (or other configuration options) once we get the first one set up.

2020-11-13 18:47 UTC, fangism commented on .github/workflows/success.sh
> +    git tag $TAG || true
general: "quote-protect" variable uses, so `"$TAG"`

2020-11-13 18:47 UTC, fangism commented on Docker/docker-run.sh
> +    IMAGE=verible:$DIR-$TAG
Recommend: `"verible:$DIR-$TAG"`

2020-11-16 10:18 UTC, fangism approved these changes

2020-11-16 10:35 UTC, wtatarski commented
@mithro  These tests fails also on other PRs so this is not the issue for this PR.

2020-11-16 15:19 UTC, wtatarski commented
Should be OK now. I introduce some small fixes. Errors in checks are related to new commits on master - I did a rebase.

2020-11-16 17:13 UTC, fangism commented
> Should be OK now. I introduce some small fixes. Errors in checks are related to new commits on master - I did a rebase.

Fix coming.

2020-11-16 22:53 UTC, fangism commented
> > Should be OK now. I introduce some small fixes. Errors in checks are related to new commits on master - I did a rebase.
> 
> Fix coming.

Can you sync to top-of-tree one more time?

2020-11-17 09:39 UTC, wtatarski commented
Looks like it is OK now. Here are github actions tests https://github.com/antmicro/verible/actions/runs/367735747

2020-11-17 09:57 UTC, fangism commented
> Looks like it is OK now. Here are github actions tests https://github.com/antmicro/verible/actions/runs/367735747

Great progress, let's pull this one in immediately.

2020-11-17 10:05 UTC, fangism commented
> > Looks like it is OK now. Here are github actions tests https://github.com/antmicro/verible/actions/runs/367735747
> 
> Great progress, let's pull this one in immediately.

The other io_kythe failure looks like https://github.com/google/verible/issues/584, so that might be the next thing.

2020-11-17 10:13 UTC, wtatarski commented
@fangism  so you want me to take a look on #584? Becasue I pick #350 earlier, but if this is more important I can take a look at this.

2020-11-17 11:04 UTC, fangism commented
> @fangism so you want me to take a look on #584? Becasue I pick #350 earlier, but if this is more important I can take a look at this.

#584 is kind of blocking releases at the moment, so probably more important.  I commented in #584 that it might be simple a matter of installing `git` on the executor.  Could you try that and see if the builds get farther along?  (And let us know how far you get.). Thanks again for your help.

2020-11-17 18:26 UTC, closed without merging